FROM rocker/r-ver:4.1.0

# ARG WHEN

WORKDIR /TechnicalTest

# Make the home directory
WORKDIR /MosaicTX/TechnicalTest

RUN apt-get update

# Dependancies
# RUN apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
# RUN apt-get update && apt-get -y install libssl-dev libxml2 libxml2-dev libgsl-dev zlib1g-dev imagemagick libpq-dev  

# prepare the environment
Rscript -e 'install.packages("devtools",repos="https://cloud.r-project.org2)'
Rscript -e 'devtools::install_github("HaMar65/MosaicTX")'

# Run the analysis
Rscript -e 'library(MosaicTX);example(CalculateAssociationsTable)'


